version: "3.8"

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=dev-db-root-pass
    volumes:
      - ./local_docker_development/.my.cnf:/root/.my.cnf
      - ./local_docker_development/my.cnf:/etc/mysql/conf.d/dev.cnf

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=mysql

  php:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./source/:/srv/
